### ISSUE TITLE
possibility to see ratings in 0.01 increments but selecting only in increments with 1

### ISSUE THREAD

**Issue by lsascha** [craigh411/vue-rate-it#6]
Hello,

i just found this nice library and am using it.
Only small issue i found is when i wanted to allow the user to only send values in increments like 1
however display the whole rating as exact as  possible and as such setting the increment value to 0.01.

I tried it by setting the increment on mouseenter to 1 and on mouseleave to 0.01 however after mouseleave the previous rating value is still displayed as a full value like 3 instead of 2.6.

Hope that was understandable. :)

**Comment by craigh411** [comment]
I'm not entirely sure how you want this to work, so I'll give you a couple of examples on what I think you're trying to achieve:

If you want to select the entire star when the user selects a value then you can use a watcher to watch for the change of the rating value and update it:

**Markup**

```HTML
<div id="app">
    <star-rating :increment="0.01" :fixed-points="2" v-model="rating"></star-rating>
</div>
```

**View Model**

```JavaScript
new Vue({
  el: "#app",
  watch:{
    rating(rating){
      this.rating = Math.ceil(rating);
    }
  },
  data: {
    rating: 2.34
  }
})
```

Here's the [JSFiddle](https://jsfiddle.net/d6vkyco8/)

Alternatively, if you want to start with an accurate rating and then only show increments of 1 things get a little trickier, but what I would do is bind the increment to a data property and then attach `mouseenter` and `mouseleave` events:

**Markup**
```HTML
  <div ref="stars">
    <star-rating :increment="increment" :fixed-points="2" v-model="rating"></star-rating>
  </div>
```

**View Model** 
```JavaScript
new Vue({
  el: "#app",
  mounted() {
    this.$refs.stars.addEventListener('mouseenter', () => {
      this.increment = 1;
    });
    this.$refs.stars.addEventListener('mouseleave', () => {
      this.increment = 0.01;
      let cachedRating = this.rating;
      this.rating = 0;
      this.$nextTick(() => {
          this.rating = cachedRating;  
      });
    });
  },
  data: {
    rating: 2.34,
    increment: 0.01
  }
})
```

Here I'm simply using a `ref` on a wrapper div so I can add some event listeners which change the increment. You may notice the unsetting and then resetting of the rating value in [$nextTick](https://vuejs.org/v2/api/#Vue-nextTick). This is simply to force `Vue` to update the DOM because the rating value hasn't changed, unfortunately I haven't found a cleaner way to do this yet. Here's the [JSFiddle](https://jsfiddle.net/2hwcf4e6/) 

I will consider whether something like this is worthwhile putting in, maybe something like `start-value` which will allow you to set an initial value regardless of the increment.

**Comment by lsascha** [comment]
thank you. the second example with $nextTick is exactly what i was missing.
its because its a voting where it displays the average voting of all people (which can be a float value)
But the single people are only allowed to vote full stars.

Only thing i changed now is that first it should not call the event that the value in the data should be send when mouseleave is called. (because it assigns it to this.rating).
And that i use the vue events so i don't need a div wrapped around it.

**Markup**
```html
<star-rating :increment="increment" :fixed-points="2" v-model="rating" @mouseenter.native="mouseEnter()" @mouseleave.native="mouseLeave()"></star-rating>
```

**View Model**
```javascript
new Vue({
  el: "#app",
  props: ['ratinguri'],
  mounted() {
    this.$refs.stars.addEventListener('mouseenter', () => {
      this.increment = 1;
    });
    this.$refs.stars.addEventListener('mouseleave', () => {
      this.increment = 0.01;
      let cachedRating = this.rating;
      this.rating = 0;
      this.$nextTick(() => {
          this.rating = cachedRating;  
      });
    });
  },
  data: {
    rating: 2.34,
    increment: 0.01,
    ratingInitialized: false
  },
  watch: {
    rating: function(value) {
        if (this.ratingInitialized) { // prevent sending the initial rating
            let url = this.ratinguri.replace('__VALUE__', value);
            this.axios.get(url).then(response => {
                var jsonData = response.data;

                if (jsonData.error) {
                    // something when voting failed
                }

            });
        }

        this.ratingInitialized = true;
    }
  },
  methods: {
    mouseEnter: function () {
        this.increment = 1;
    },
    mouseLeave: function () {
        this.increment = 0.01;

        // prevent double sending
        this.ratingInitialized = false;

        let cachedRating = this.dataRating;
        this.rating = 0;
        this.$nextTick(() => {
            this.ratingInitialized = false;
            this.rating = cachedRating;
        });
    }
  }
})
```

here is a simpler [JSFiddle](https://jsfiddle.net/t63mnoxp/)
