### ISSUE TITLE
Improve package size

### ISSUE THREAD

**Issue by hdl-helsinki** [craigh411/vue-rate-it#9]
font-awesome increases almost 1mb the size of my production script.

 think it would be better to load the icons via css or, at least, remove the unneeded icons.

Thank you

**Comment by craigh411** [comment]
Absolutely, I will be sorting this out as soon as I get the chance. The font awesome icons need to be SVG paths, but it certainly isn't necessary to import all icons, so I will look at the best way to remove these from the bundle while still allowing a simple method of importing only the required icon. I have a couple of ideas, so expect an update soon.

**Comment by hdl-helsinki** [comment]
Thank you very much.

Maybe you could parse the SVG icons from bootstrap CDN: https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.svg

**Comment by dmaicher** [comment]
Any update on this issue? :blush: 

I would also like to use your plugin but my js package size increases by 720KB (minified) which is not acceptable for me.

I only really want to use the `ImageRating` without all the icon stuff.

**Comment by craigh411** [comment]
This issue has now been resolved in Version 2.0 and `vue-rate-it` is now 18.6 KB. Because it was the font-awesome glyphs that were causing the file bloat there are some changes to how the `fa-rating` component works, which are documented in the [release notes](https://github.com/craigh411/vue-rate-it/releases/tag/v2.0.0). All other rating components work the same as before, so there shouldn't be any issues upgrading to 2.0 if you are using those.
